export const config = {

    configOverwrite: {
        startWithAudioMuted: true,
        disableInviteFunctions: true,
        logoClickUrl: "",
        logoImageUrl: "",
        toolbarButtons: [
            "camera",
            "chat",
            "closedcaptions",
            "desktop",
            "etherpad",
            "filmstrip",
            "fullscreen",
            "hangup",
            "help",
            "invite",
            "microphone",
            "mute-everyone",
            "mute-video-everyone",
            "participants-pane",
            "raisehand",
            "recording",
            // 'security',
            "select-background",
            // 'settings',
            "shareaudio",
            "sharedvideo",
            "shortcuts",
            "tileview",
            "toggle-camera",
            "videoquality",
            "__end",
        ],
    },
    interfaceConfigOverwrite: {
        DEFAULT_BACKGROUND: "#2F3C55",
        HIDE_INVITE_MORE_HEADER: true,
        SHARING_FEATURES: [],
        SHOW_PROMOTIONAL_CLOSE_PAGE: false,
        AUDIO_LEVEL_PRIMARY_COLOR: "#2BB998",
        AUDIO_LEVEL_SECONDARY_COLOR: "#2BB99855",
        DEFAULT_LOGO_URL: "",
        JITSI_WATERMARK_LINK: "",
        SHOW_JITSI_WATERMARK: false,
        SHOW_WATERMARK_FOR_GUESTS: false,
    },
};
